export interface song {
    song: string, 
    lyrics?: string
}

export const sampleSongs: song[] = [
    {
        song: "Babe I'm Gonna Leave you",
        lyrics: "Babe, baby, baby, I'm gonna leave you\nI said baby, you know I'm gonna leave you\nI'll leave you when the summertime\nLeave you when the summer comes a rollin'\nLeave you when the summer comes along\nBabe, babe, babe, babe, babe, babe, baby, baby\nI don't want to leave you\nI ain't jokin' woman, I got to ramble\nOh yeah\nBaby, baby, babe, I believin'\nWe really got to ramble\nI can hear it callin' me the way it used to do\nI can hear it callin' me back home\nBabe, I'm gonna leave you\nOh, baby, you know, I've really got to leave you\nOh I can hear it callin 'me\nI said don't you hear it callin' me the way it used to do?\nOh\nI know, I know\nI know I never never never never never gonna leave your babe\nBut I got to go away from this place\nI've got to quit you, yeah\nOoh, baby baby baby baby baby baby ooh\nDon't you hear it callin' me?\nWoman, woman, I know, I know\nIt feels good to have you back again\nAnd I know that one day baby, it's really gonna grow, yes it is\nWe gonna go walkin' through the park every day\nCome what may, every day\nOh, mama baby\nI'm gonna leave you go away\nIt was really, really good\nYou made me happy every single day\nBut now\nI've got to go away\nBaby, baby, baby\nThat's when it's callin' me\nI said that's when it's callin' me back home"
    },
    {
        song: "Communication Breakdown",
        lyrics: "Hey, girl, stop what you're doin'\n\nHey, girl, you'll drive me to ruin\nI don't know what it is I like about you, but I like it a lot\nWon't you let me hold you, now, let me feel your lovin' touch\nCommunication breakdown, it's always the same\nHavin' a nervous breakdown, a-drive me insane\nHey, girl, I got somethin' I think you oughta know\nHey, babe, I wanna tell ya that I love you so\nI wanna hold you in my arms, yeah\nI'm never gonna let you go, 'cause I like your charm\nCommunication breakdown, it's always the same\nHavin' a nervous breakdown, drive me insane, ow, suck\nCommunication breakdown, it's always the same\nHavin' a nervous breakdown, a-drive me insane, yeah\nCommunicate, I want you to love me all night\nI want you to love me all night, I want, hey, I want, yeah\nI want you to love me, I want you to love, babe\nI want you to love, yeah, I want you to love\nHey, I want you to love, yeah, I want you to"
    },
    {
        song: "Dazed and Confused",
        lyrics: "Been dazed and confused\n\nFor so long, it's not true\nWanted a woman, never bargained for you\nLotsa people talkin',\nFew of them know\nSoul of a woman was created below, yeah\nYou hurt and abuse,\nTellin' all of your lies\nRun 'round, sweet baby, lord, how they hypnotize\nSweet little baby, I don't know where you been\nGonna love you, baby, here I come again\nEvery day I work so hard, bringin' home my hard-earned pay\nTry to love you, baby, but you push me away\nDon't know where you're goin',\nOnly know just where you've been\nSweet little baby, I want you again\nAh, ah, ah, ah\n(Did you ever look up my woman)\nAh, ah-ah-ah, ah-ah-ah-ah, ah-ah-ah-ah\nAh-ah-ah-ah-ah-ah-ah-ah-ah-ah, ah\nAhh, ah, ah, ah, ah\nAh-ah-ah-ah-ah-ah-ah-ah-ah-ah-ah-ah-ah-ah-ah-ahhh, ahh\nOh, yeah, alright, alright\nAh, ah, ah, ah, ah-ah-ah, ah-ah-ah, ah\nAh-ah, ah-ah, ah-ah, ah-ah\nOh, I don't like when you're mystifyin' me\nOh, don't leave me so confused, now\nWhoa, baby\nBeen dazed and confused for so long, it's not true\nWanted a woman, never bargained for you\nTake it easy, baby,\nLet them say what they will\nTongue wag so much when I send you the bill,\nOh, yeah, alright"
    },
    {
        song: "Good Times Bad Times",
        lyrics: "In the days of my youth\nI was told what it means to be a man\nNow I've reached that age\nI've tried to do all those things the best I can\nNo matter how I try\nI find my way to the same old jamGood times, bad times\nYou know I've had my share\nWhen my woman left home\nFor a brown-eyed man\nWell, I still don't seem to care\nSixteen I fell in love\nWith a girl as sweet as could be\nIt only took a couple of days\n'Til she was rid of me\nShe swore that she would be all mine\nAnd love me 'til the end\nBut when I whispered in her ear\nI lost another friend\nGood times, bad times\nYou know I've had my share\nWhen my woman left home\nFor a brown eyed man\nWell, I still don't seem to care\nGood times, bad times\nYou know I've had my share\nWhen my woman left home\nFor a brown eyed man\nBut, I still don't seem to care\nI know what it means to be alone\nI sure do wish I was at home\nI don't care what the neighbors say\nI'm gonna love you each and every day\nYou can feel the beat within my heart\nRealize, sweet babe, we ain't ever gonna part"
    },
    {
        song: "How Many More Times",
        lyrics: "How many more times, treat me the way you wanna do\nHow many more times, treat me the way you wanna do\nWhen I give you all my love, please, please be true\nI'll give you all I've got to give, rings, pearls, and all\nI'll give you all I've got to give, rings, pearls, and all\nI've got to get you together baby, I'm sure, sure you're gonna crawl\nI was a young man, I couldn't resist\nStarted thinkin' it over, just what I had missed\nGot me a girl and I kissed her and then and then\nWhoops, oh lord, well I did it again\nNow I've got ten children of my own\nI got another child on the way that makes eleven\nBut I'm in constant heaven\nI know it's all right in my mind\n'Cause I got a little schoolgirl and she's all mine\nI can't get through to her 'cause it doesn't permit\nBut I'm gonna give her everything I've got to give\nOh, Rosie, oh, girl, oh, Rosie, oh, yeah\nSteal away now, steal away\nSteal away, baby, steal away\nLittle Robert Anthony wants to come and play\nWhy don't you come for me, baby, steal away, alright, alright\nWell, they call me the hunter, that's my name\nCall me the hunter, that's how I got my fame\nAin't no need to hide, ain't no need to run\n'Cause I've got you in the sights of my gun\nHow many more times, barrel house all night long\nHow many more times, barrel house all night long\nWell I've got to get to you, baby, oh, please come home\nWhy don't you listen to me, babe\nWhy don't you please come home\nWhy don't you please come home\nWhy don't you please come home"
    },
    {
        song: "What Is and What Should Never Be",
        lyrics: "And if I say to you tomorrow\nTake my hand, child come with me\nIt's to a castle I will take you\nWhere what's to be, they say will be\nCatch the wind, see us spin\nSail away leave today\nWay up high in the sky, hey, whoa\nBut the wind won't blow\nYou really shouldn't go\nIt only goes to show\nThat you will be mine\nBy takin' our time, ooh\nAnd if you say to me tomorrow\nOh what fun it all would be\nThen what's to stop us, pretty baby\nBut what is and what should never be\nCatch the wind, see us spin\nSail away, leave today\nWay up high in the sky, hey whoa\nBut the wind won't blowYou really shouldn't go\nOnly goes to show\nThat you will be mine\nBy takin' our time, ooh\nSo if you wake up with the sunrise\nAnd all your dreams are still as new\nAnd happiness is what you need so bad\nGirl, the answer lies with you, yeah\nCatch the wind, see us spin\nSail away, leave today\nWay up high in the sky, hey whoa\nBut the wind won't blow\nYou really shouldn't go\nOnly goes to show\nThat you will be mine\nBy takin' our time, ooh\nHey, oh\nOh the wind won't blow and we really shouldn't go\nAnd it only goes to show-ow-ow\nCatch the wind, we're gonna see it spin\nWe're gonna sail, little girl\nDo do do, bop bop a do-oh\nMy my my my my my my yeah\nEverybody I know seems to know me well\nBut does anybody know I'm gonna move like hell\nBaby, baby, baby, baby, baby, baby, oh, Lord\nBaby, baby, baby, oh, right now, yeah\nNo, no, no, no, no, come on, now"
    },
    {
        song: "Whole Lotta Love",
        lyrics: "You need cooling\nBaby I'm not fooling\nI'm gonna send ya\nBack to schooling\nA-way down inside\nA-honey you need it\nI'm gonna give you my love\nI'm gonna give you my love\nWant to whole lotta love\nWant to whole lotta love\nWant to whole lotta love\nWant to whole lotta love\nYou've been learning\nUm baby I been learning\nAll them good times baby, baby\nI've been year-yearning\nA-way, way down inside\nA-honey you need-ah\nI'm gonna give you my love, ah\nI'm gonna give you my love, ah oh\nWhole lotta love\nWant to whole lotta love\nWant to whole lotta love\nWant to whole lotta love\nYou've been cooling\nAnd baby I've been drooling\nAll the good times, baby\nI've been misusing\nA-way, way down inside\nI'm gonna give ya my love\nI'm gonna give ya every inch of my love\nI'm gonna give ya my love\nHey!\nAlright! Let's go!\nWhole lotta love\nWant to whole lotta love\nWant to whole lotta love\nWant to whole lotta love\nWay down inside\nWoman, you need, yeah\nLove\nMy, my, my, my\nMy, my, my, my\nLord\nShake for me girl\nI wanna be your backdoor man\nHey, oh, hey, oh\nHey, oh, hey, oh\nOoh\nOh, oh, oh, oh\nCool, my, my baby\nA-keep it cooling baby\nA-keep it cooling baby\nAh-keep it cooling baby\nAh-keep it cooling baby\nAh-keep it cooling baby\n"
    },
    {
        song: "You shook me",
        lyrics: "You know you shook me\nYou shook me all night long.\nYou know you shook me, baby\nYou shook me all night long.\nYou shook me so hard baby\nBaby, baby, please come home.\nI have a bird that whistles\nAnd I have birds that sing.\nI have a bird that whistles\nAnd I have birds that sing.\nI have a baby, won't do nothing oh!\nOh, oh, buy a diamond ring.\nYou know you shook me, baby\nYou shook me all night long.\nI know you really, really, did baby.\nI said you shook me, baby.\nYou shook me all night long.\nYou shook me so hard, baby.\nYou shook me all night long\n"
    },
    {
        song: "Your Time Is Gonna Come",
        lyrics: "Lyin' Cheatin' Hurtin That's All You Seem To Do\nMessin' Around With Every Guy In Town\nPuttin' Me Down For Thinkin' Of Someone New\nAlways The Same Playin' Your Game\nDrive Me Insane Trouble Is Gonna Come To You\nOne Of These Days And It Won't Be Long\nYou'll Look For Me But Baby I'll Be Gone\nThis Is All I Gotta Say To You Woman:\nYour Time Is Gonna Come\nYour Time Is Gonna Come\nYour Time Is Gonna Come\nYour Time Is Gonna Come\nMade Up My Mind To Break You This Time\nWon't Be So Fine It's My Turn To Cry\nDo Want You Want I Won't Take The Brunt\nIt's Fadin' Away Can't Feel You Anymore\nDon't Care What You Say 'Cause I'm Goin' Away To Stay\nGonna Make You Pay For That Great Big Hole In My Heart\nPeople Talkin' All Around\nWatch Out Woman No Longer\nIs The Joke Gonna Be On My Heart\nYou Been Bad To Me Woman\nBut It's Coming Back Home To You\n"
    },
    {
        song: "Black Mountain Side"
    }
]